# Generated by Django 4.0.3 on 2022-04-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('usertype', models.CharField(choices=[('ADMIN', 'ADMIN'), ('CUSTOMER', 'CUSTOMER')], max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
