# Generated by Django 4.0.3 on 2022-04-09 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationModel',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SourceModel',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlightPriceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_flight_time', models.DateField()),
                ('next_flight_time', models.DateField()),
                ('flight_category', models.CharField(choices=[('ECONOMY', 'ECONOMY'), ('PREMIUM_ECONOMY', 'PREMIUM_ECONOMY'), ('FIRST_CLASS', 'FIRST_CLASS'), ('BUSINESS_CLASS', 'BUSINESS_CLASS')], max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('is_available', models.BooleanField(default=False)),
                ('number_of_seats', models.IntegerField(default=0)),
                ('available_seats', models.IntegerField(default=0)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.destinationmodel')),
                ('starting_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.sourcemodel')),
            ],
        ),
    ]
